name: test

on:
  pull_request:
    types: [opened, synchronize]

  push:
    branches: [main, test]

  workflow_dispatch:

env:
  HOMEBREW_DEVELOPER: 1

jobs:
  install:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    steps:
      # This action automatically installs the locally checked out tap.
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install CLI
        run: |
          brew install databricks

      - name: Run CLI
        run: |
          databricks version
